/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;

/**
 *
 * @author xehartnort
 */
public class BadConsequenceView extends javax.swing.JPanel {
    private BadConsequence badConsequenceModel;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
    
    public void enableVisibleTreasures(boolean val){
        visibleTreasures.setVisible(val);
    }
    
    public void enableHiddenTreasures(boolean val){
        hiddenTreasures.setVisible(val);
    }
    
    public void setBadConsequence(BadConsequence bc){
        this.badConsequenceModel=bc;
        this.name.setText("Esto es un mal rollo: "+badConsequenceModel.getText());
        this.levels.setText("Niveles:"+Integer.toString(badConsequenceModel.getLevels()));
        if(badConsequenceModel instanceof NumericBadConsequence){
            this.hiddenTreasures.setText("Ocultos:"+
                Integer.toString(((NumericBadConsequence)badConsequenceModel).getNHiddenTreasures()) );
            this.visibleTreasures.setText("Visibles:"+
                Integer.toString(((NumericBadConsequence)badConsequenceModel).getNVisibleTreasures()) );
        }else{
            if(badConsequenceModel instanceof SpecificBadConsequence){
                this.hiddenTreasures.setText("Ocultos:"+
                    ((SpecificBadConsequence)badConsequenceModel).getSpecificHiddenTreasures() );
                this.visibleTreasures.setText("Visibles:"+
                        ((SpecificBadConsequence)badConsequenceModel).getSpecificVisibleTreasures() );
            }else{
                this.hiddenTreasures.setText("Ocultos:10");
                this.visibleTreasures.setText("Visibles:10"); 
            }
        }
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        levels = new javax.swing.JLabel();
        visibleTreasures = new javax.swing.JLabel();
        hiddenTreasures = new javax.swing.JLabel();

        name.setText("descripción");
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        levels.setText("levels");

        visibleTreasures.setText("visibles");

        hiddenTreasures.setText("ocultos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levels)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(visibleTreasures)
                        .addComponent(hiddenTreasures))
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(levels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visibleTreasures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hiddenTreasures))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hiddenTreasures;
    private javax.swing.JLabel levels;
    private javax.swing.JLabel name;
    private javax.swing.JLabel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
