/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Monster;

/**
 *
 * @author xehartnort
 */
public class MonsterView extends javax.swing.JPanel {
    private Monster monsterModel;
    /**
     * Creates new form MonterView
     */
    public MonsterView() {
        initComponents();
    }
    
    public void setMonster(Monster m){
        this.monsterModel = m; 
        this.name.setText("Nombre:"+monsterModel.getName());
        this.combatLevel.setText("Nivel de combate:"+Integer.toString(monsterModel.getCombatLevel()));
        this.combatLevelCultist.setText("Nivel de combarte contra cultist:"+Integer.toString(monsterModel.getCombatLevelAgainstCultistPlayer()));
        this.bc.setBadConsequence(monsterModel.getBadConsequence());
        this.prize.setPrize(monsterModel.getPrize());
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        combatLevel = new javax.swing.JLabel();
        combatLevelCultist = new javax.swing.JLabel();
        prize = new GUI.PrizeView();
        bc = new GUI.BadConsequenceView();

        name.setText("Name:");

        combatLevel.setText("Nivel de combate:");

        combatLevelCultist.setText("Nivel de combate contra cultist:");

        prize.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(combatLevel)
            .addComponent(name)
            .addComponent(combatLevelCultist)
            .addComponent(prize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(bc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combatLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combatLevelCultist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView bc;
    private javax.swing.JLabel combatLevel;
    private javax.swing.JLabel combatLevelCultist;
    private javax.swing.JLabel name;
    private GUI.PrizeView prize;
    // End of variables declaration//GEN-END:variables
}
