/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;

/**
 *
 * @author xehartnort
 */
public class NapakalakiView extends javax.swing.JFrame {
    private Napakalaki napakalakiModel;

    public NapakalakiView() {
        initComponents();
    }

    public void setNapakalaki(Napakalaki t){
        this.napakalakiModel=t;
        this.currentPlayer.setPlayer(napakalakiModel.getCurrentPlayer());
        this.currentMonster.setMonster(napakalakiModel.getCurrentMonster());
        this.currentPlayer.setNapakalaki(napakalakiModel);
        this.currentMonster.setVisible(false);
        this.meetTheMonster.setEnabled(true);
        this.combat.setEnabled(false);
        this.nextTurn.setEnabled(false);
        this.msg.setEnabled(true);
        this.currentPlayer.setBotones(true, false, false);
//        this.reiniciar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentMonster = new GUI.MonsterView();
        meetTheMonster = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        nextTurn = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        currentPlayer = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        meetTheMonster.setText("Meet the monster");
        meetTheMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetTheMonsterActionPerformed(evt);
            }
        });

        combat.setText("Combat");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        nextTurn.setText("Next Turn");
        nextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnActionPerformed(evt);
            }
        });

        msg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        msg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        msg.setText("Mensaje del juego:");
        msg.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meetTheMonster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentMonster, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(msg))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meetTheMonster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextTurn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combat)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meetTheMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetTheMonsterActionPerformed
        this.currentMonster.setVisible(true);
        this.meetTheMonster.setEnabled(false);
        this.combat.setEnabled(true);
        this.currentPlayer.setBotones(false, false, false);
        msg.setText("Juego: Este monstruo asusta, ¿verdad?");
    }//GEN-LAST:event_meetTheMonsterActionPerformed

    private void nextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnActionPerformed
        if ( napakalakiModel.nextTurn() ){
            this.nextTurn.setEnabled(false);
            this.meetTheMonster.setEnabled(true);
            this.currentPlayer.setBotones(true, false, false);
            currentPlayer.setPlayer(napakalakiModel.getCurrentPlayer());
            currentMonster.setMonster(napakalakiModel.getCurrentMonster());
            this.currentMonster.setVisible(false);
            msg.setText("Juego:");
        }else
            msg.setText("Juego: ¡ tienes que cumplir el mal rollo !");
    }//GEN-LAST:event_nextTurnActionPerformed

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        CombatResult pelea = this.napakalakiModel.developCombat();
        if( napakalakiModel.endOfGame(pelea) )
        {
            this.currentPlayer.setBotones(false, false, false);
            this.nextTurn.setEnabled(false);
//            this.reiniciar.setEnabled(true);
        }else{
            this.currentPlayer.setBotones(false, true, true);
            this.nextTurn.setEnabled(true);   
        }
        if(pelea == CombatResult.LOSE)
            msg.setText("Juego: has perdido el combate");
        if(pelea == CombatResult.LOSEANDCONVERT)
            msg.setText("Juego: has perdido y te conviertes en sectáreo");
        if(pelea == CombatResult.WIN)
            msg.setText("Juego: has ganado el combate");
        if(pelea == CombatResult.WINGAME)
            msg.setText("Juego: has ganado el juego, enhorabuena");
        this.combat.setEnabled(false);
        currentPlayer.setPlayer(napakalakiModel.getCurrentPlayer());
        
    }//GEN-LAST:event_combatActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private GUI.MonsterView currentMonster;
    private GUI.PlayerView currentPlayer;
    private javax.swing.JButton meetTheMonster;
    private javax.swing.JLabel msg;
    private javax.swing.JButton nextTurn;
    // End of variables declaration//GEN-END:variables
}
